using SceneForge.Media.Domain;
using SceneForge.Media.Extraction;

namespace SceneForge.Media.Planning;

// Everything one TimelinePlanner.Plan run needs. AvailableClips is a plain
// caller-supplied fact - typically CleanClipExtractionResult.AcceptedClips
// - TimelinePlanner never re-scores, re-clusters, or otherwise second-
// guesses which clips are usable (clean architecture: that judgment belongs
// to CleanClipExtractor, not the planner).
public sealed record TimelinePlanRequest
{
    private readonly int _minimumRepeatDistance = 1;
    private readonly int _maximumReuseCount = 1;
    private readonly int _originalNeighborSeparation = 1;
    private readonly int _visualClusterAdjacencyLimit = 1;

    public required IReadOnlyList<CleanClip> AvailableClips { get; init; }

    public required TimeSpan TargetAudioDuration { get; init; }

    // Frame rate the planned timeline will ultimately be exported at.
    // TargetAudioDuration is rounded to the nearest whole frame count at
    // this rate before planning begins (see TimelinePlan.QuantizedTargetDuration/
    // TargetFrameCount/AudioDurationRoundingError) so "matches the audio
    // duration exactly" is answered in the output's own time base, not an
    // arbitrary tick count no encoder could reproduce as a cut point.
    public required RationalFrameRate OutputTimeBase { get; init; }

    // Deterministic seed: the same seed against the same AvailableClips and
    // every other field here always produces the same plan (see
    // TimelinePlanner and Internal.ClipShuffleOrder).
    public required int Seed { get; init; }

    public TimelineDurationBounds DurationBounds { get; init; } = TimelineDurationBounds.Default;

    // Minimum number of OTHER placements required between two placements
    // of the same clip (index into AvailableClips) - i.e. the position
    // distance between them must exceed this value. 0 permits back-to-back
    // immediate duplicates; 1 (the default) forbids only literally adjacent
    // repeats (distance 1) while still permitting a repeat one slot later.
    public int MinimumRepeatDistance
    {
        get => _minimumRepeatDistance;
        init => _minimumRepeatDistance = Math.Max(0, value);
    }

    // Hard cap on how many times any single clip may appear in the plan.
    // Unlike every other constraint here, this one is never relaxed - see
    // TimelinePlanner's tiered relaxation order and
    // TimelinePlan.FeasibilityWarning for what happens when it makes the
    // target duration unreachable. Clamped to at least 1: a clip usable
    // zero times is not a usable clip.
    public int MaximumReuseCount
    {
        get => _maximumReuseCount;
        init => _maximumReuseCount = Math.Max(1, value);
    }

    // Minimum number of OTHER placements required between two clips that
    // share a CleanClip.SourceSceneIndex (same distance semantics as
    // MinimumRepeatDistance above). This is the single knob
    // covering both "avoid neighboring clips from the same source scene"
    // and, as a direct consequence, "avoid preserving long contiguous
    // source order" - clips generated by CleanClipExtractor from one scene
    // range are exactly the clips whose original order would otherwise be
    // preserved, so keeping same-scene placements apart is what breaks
    // contiguity (see docs/PHASE_08_REPORT.md, Design summary).
    public int OriginalNeighborSeparation
    {
        get => _originalNeighborSeparation;
        init => _originalNeighborSeparation = Math.Max(0, value);
    }

    // Minimum number of OTHER placements required between two clips that
    // share a CleanClip.ClusterId (same distance semantics as
    // MinimumRepeatDistance above). A clip with a null ClusterId (never
    // clustered) is never constrained by this rule against any other clip.
    public int VisualClusterAdjacencyLimit
    {
        get => _visualClusterAdjacencyLimit;
        init => _visualClusterAdjacencyLimit = Math.Max(0, value);
    }
}
