<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SceneForge.Core\SceneForge.Core.csproj" />
    <ProjectReference Include="..\SceneForge.Media\SceneForge.Media.csproj" />
    <ProjectReference Include="..\SceneForge.Infrastructure\SceneForge.Infrastructure.csproj" />
  </ItemGroup>

</Project>
